### ISSUE TITLE
ETA for driving patches upstream

### ISSUE THREAD

**Issue by StuartAndersonIntel** [intel/iotg_tsn_ref_sw#28]
What is the ETA for driving the patches for external libraries upstream? Having to patch external librareis is problematic, and prevents this software from being packaged and incorporated into the Linux Distributions (or our internal systems that follow the same rules).

**Comment by AzuraTarmiziIntel** [comment]
Hi Stuart, 
The patches we are providing is to support XDP_TBS (intel current driver implementation). However this driver implementation is now being reworked due to changes in AF_XDP framework itself. Once we have the framework ready, we will upgrade the driver to follow suit, and try to upstream the driver patches first. then tsn ref sw will follow the upstreamed implementation naturally. 

To answer you, no we dont have ETA set is stone yet. It is highly depending on the AF_XDP framework effort and stmmac/igc driver development effort as well. Hope that answers.
