### ISSUE TITLE
Unknown qdisc "taprio", hence option is unparsable

### ISSUE THREAD

**Issue by EnfangCui** [intel/iotg_tsn_ref_sw#5]
I used the ubuntu 18.04 with Linux kernel 5.0.1 including "taprio" drivers at Networking support --> Networking options --> QOS and /or fair queueing. But when I run the "tc qdisc replace dev eth0 parent root handle 100 taprio " command, it gives error: "Unknown qdisc "taprio", hence option is unparsable".  I wonder how to make the Linux support taprio.  Can you give me a more detailed kernel configuration?  Look forward to your kind reply. Thanks!

**Comment by vincentxw** [comment]
Hi, there's 2 things. 

If you enabled TAPRIO qdisc as a module, make sure you load it via modprobe sch_taprio.

Next, your Ubuntu's TC (part of iproute2) may not be of the latest version. You can get the iproute2 version we used [here](https://github.com/intel/iotg-yocto-bsp-public/blob/MR4rt-B-01/meta-intel-tsn/recipes-connectivity/iproute2/iproute2_git.bb). Use the specific commit as the TAPRIO tc command has changed since the time we wrote these set of applications.

**Comment by EnfangCui** [comment]
Thank you very much. I installed the latest version of iproute2 and solved the problem.

**Comment by EnfangCui** [comment]
Have you recompiled the kernel and turned on the corresponding kernel options？

**Comment by kcn21** [comment]
> @kcn21 Have you recompiled the kernel and turned on the corresponding kernel options？

@EnfangCui  No. What specific option do I have to follow? I have executed the following steps till now.
1. I have cloned the iproute2 from the following link
https://github.com/shemminger/iproute2https://github.com/shemminger/iproute2

2, sudo make

3. sudo make install

I have upgraded iproute2 to another PC and it worked but on my PC it is showing specified qdisc not found error.

**Comment by liing0228** [comment]
@kcn21 did you fix the issue ?
i faced the same issue right now and i am using kernel 4.20 and 5.4.
If you can help me i will be grateful.

**Comment by kcn21** [comment]
> @kcn21 did you fix the issue? I faced the same issue right now, and i am using kernel 4.20 and 5.4. If you can help me, i will be grateful.

Hello @liing0228, you have to enable modules for taprio in the kernel, but many kernels didn't have modules for the TAPRIO, so I think that's why you are facing this issue. Please prefer kernel above 5.0 versions if you didn't have dependencies on kernel versions.

Hello @EnfangCui and @vincentxw, I am following tsn.readthdocs.io for AVB examples, and they have written to use the 4.19 kernel for AVB examples. I also tried kernel version 5.12, but it shows an AAF PDU error and abruptly stops the sending. So I have to use  Linux Kernel 4.19. Still, in Linux Kernel 4.19, there are no options to enable the TAPRIO module in the kernel under Networking support --> Networking options --> QOS and /or a fair queueing section.  
Can you please show a way to add a qdisc module in the kernel?  I have updated the iproute2 also, but as there is no module for taprio in the kernel, there is no advantage of iproute2 degradation.  Your guidance in this situation is highly appreciated

Thanks,
Kunj Naik
